// <auto-generated />
namespace Whatfits.Models.Migrations.RegistrationMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addclaims : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addclaims));
        
        string IMigrationMetadata.Id
        {
            get { return "201803051837035_add-claims"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
