// <auto-generated />
namespace Whatfits.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class workoutlogcomplete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workoutlogcomplete));
        
        string IMigrationMetadata.Id
        {
            get { return "201802202330256_workoutlogcomplete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
