// <auto-generated />
namespace Whatfits.Models.Migrations.ContentMigrations.NotificationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Notifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201804222125086_Notifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
