// <auto-generated />
namespace Whatfits.Models.Migrations.CoreMigrations.RegistrationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class claimsfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(claimsfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201803062332216_claims fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
